<html>
<head>
    <title>Example Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1 style="color: #aa0000; text-align: center">Ooooops!</h1>
<?php
include_once "hiba.php";
$exception=new hiba();
?>
<p style="color: red; text-align:center"><b style="text-align: center">Üzenet a weblapról: </b> <?=$exception->hibas();
?></p>
<p><?=$exception->getLine();?><?=$exception->getFile();?></p>
<p style="text-align: center"><img src="image/stop.png" style="background: center"></p>
</body>
</html>
